### PR TITLE
Refund Payment Working from Admin

### PR DESCRIPTION
**Pull request by rdr6000**
Refund from admin was not working due to fetch payment id block. I have updated the code and its currently working now.

### CODE REVIEW

**Comment by rdr6000** [comment]
image

I am skipping all of this:

image

and replacing with this:

image

Using fetchPayments I get the payments block directly where as paymentIntent.payments was empty. This solves the refund issue
@SGFGOV

**Comment by SGFGOV** [comment]
Hey thanks. Good attempt but this may not work always especially when the amount is different from the the amount being refunded

**Comment by SGFGOV** [comment]
Plz add tests also to validate the fix

**Review by Kushal2024 — APPROVED** [review]

**Review by SGFGOV — APPROVED** [review]
I think this looks ok

**Review by SGFGOV — APPROVED** [review]
ok

**Pull request merged**
